<a href="https://colab.research.google.com/github/Lukas-Howlett/DenverCoffeeShop/blob/main/DenverCoffeeShop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# A new coffee shop wants to open stores in Denver and believes that the ideal location is near affluent households and that their store appeals most to those aged 20-35.

## We want to find neighborhoods with high populations of people aged 20-35 near affluent neighborhoods.

### Don't have to worry about competition from Starbucks since the coffee shop doesn't particularly compete with them.

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
coffee_df = pd.read_csv("/content/sample_data/denverCoffeeShop.csv")

In [ ]:
display(coffee_df)

,NBHD_ID,NBHD_NAME,POPULATION_2010,AGE_LESS_18,AGE_18_TO_34,AGE_35_TO_65,AGE_65_PLUS,NUM_HOUSEHOLDS,FAMILIES,NUM_HHLD_100K+
0,1,Athmar Park,8898.0,2649.0,2406.0,3112.0,731.0,2781.0,1964.0,425.0
1,2,Auraria,705.0,7.0,635.0,57.0,6.0,60.0,15.0,NaN
2,3,Baker,4879.0,745.0,1762.0,2037.0,335.0,2447.0,833.0,NaN
3,4,Barnum,6111.0,2015.0,1647.0,2089.0,360.0,1782.0,1289.0,120.0
4,5,Barnum West,5376.0,1579.0,1380.0,1824.0,593.0,1704.0,1207.0,NaN
...,...,...,...,...,...,...,...,...,...,...
73,74,West Colfax,9740.0,2756.0,2935.0,3111.0,938.0,3703.0,1971.0,431.0
74,75,West Highland,8540.0,1304.0,2555.0,3756.0,925.0,4256.0,1853.0,1725.0
75,76,Westwood,15486.0,5678.0,4037.0,4712.0,1059.0,4340.0,3306.0,326.0
76,77,Whittier,4831.0,1119.0,1586.0,1788.0,338.0,1993.0,1008.0,NaN
77,78,Windsor,12589.0,1819.0,3302.0,4085.0,3383.0,7204.0,2590.0,723.0

In [ ]:
coffee_df[coffee_df['NUM_HHLD_100K+'] > 0].sort_values(by=['AGE_18_TO_34'], ascending=False)

,NBHD_ID,NBHD_NAME,POPULATION_2010,AGE_LESS_18,AGE_18_TO_34,AGE_35_TO_65,AGE_65_PLUS,NUM_HOUSEHOLDS,FAMILIES,NUM_HHLD_100K+
8,9,Capitol Hill,14708.0,408.0,8274.0,5155.0,871.0,10856.0,1201.0,1223.0
27,28,Gateway - Green Valley Ranch,29201.0,10074.0,7778.0,10405.0,944.0,9427.0,7056.0,2192.0
44,45,Montbello,30348.0,11137.0,7742.0,9561.0,1908.0,7942.0,6399.0,939.0
25,26,Five Points,12712.0,1446.0,5961.0,4660.0,645.0,6406.0,1711.0,1680.0
63,64,University,9375.0,826.0,5784.0,2246.0,519.0,3759.0,1218.0,991.0
58,59,Speer,10954.0,707.0,5361.0,3970.0,916.0,7304.0,1400.0,1682.0
31,32,Hampden,17547.0,2754.0,4655.0,6957.0,3181.0,9320.0,4105.0,2160.0
75,76,Westwood,15486.0,5678.0,4037.0,4712.0,1059.0,4340.0,3306.0,326.0
59,60,Central Park,13948.0,3516.0,4008.0,6045.0,379.0,4092.0,2759.0,2748.0
71,72,Washington Virginia Vale,13030.0,2252.0,3984.0,4798.0,1996.0,6646.0,2808.0,1047.0
68,69,Virginia Village,12844.0,2421.0,3754.0,5058.0,1611.0,6056.0,2860.0,1129.0
32,33,Hampden South,14370.0,2639.0,3729.0,5650.0,2352.0,7243.0,3481.0,2158.0
19,20,Congress Park,10235.0,1427.0,3614.0,4450.0,744.0,5724.0,1940.0,1680.0
23,24,East Colfax,10191.0,2595.0,3397.0,3640.0,559.0,4273.0,2106.0,442.0
77,78,Windsor,12589.0,1819.0,3302.0,4085.0,3383.0,7204.0,2590.0,723.0
35,36,Highland,8429.0,1296.0,3269.0,3070.0,794.0,4131.0,1495.0,1704.0
11,12,Cheesman Park,7971.0,510.0,3268.0,3241.0,952.0,5343.0,1000.0,1055.0
42,43,Mar Lee,12452.0,3685.0,3256.0,4289.0,1222.0,3973.0,2771.0,413.0
46,47,North Capitol Hill,5823.0,194.0,3238.0,1968.0,423.0,3851.0,461.0,1010.0
43,44,Marston,11132.0,2266.0,3119.0,4553.0,1194.0,5206.0,2821.0,1164.0
33,34,Harvey Park,11525.0,3162.0,3005.0,4107.0,1251.0,3990.0,2772.0,476.0
65,66,University Park,7491.0,1135.0,2936.0,2559.0,861.0,3663.0,1408.0,1080.0
73,74,West Colfax,9740.0,2756.0,2935.0,3111.0,938.0,3703.0,1971.0,431.0
61,62,Sunnyside,9726.0,2363.0,2829.0,3593.0,941.0,3781.0,2222.0,851.0
74,75,West Highland,8540.0,1304.0,2555.0,3756.0,925.0,4256.0,1853.0,1725.0
40,41,Lincoln Park,6119.0,1365.0,2457.0,1867.0,430.0,2741.0,1044.0,364.0
67,68,Villa Park,8758.0,2741.0,2422.0,2912.0,683.0,2819.0,1834.0,291.0
0,1,Athmar Park,8898.0,2649.0,2406.0,3112.0,731.0,2781.0,1964.0,425.0
53,54,Ruby Hill,9820.0,2865.0,2397.0,3440.0,1118.0,3324.0,2146.0,364.0
5,6,Bear Valley,8889.0,2036.0,2375.0,3190.0,1288.0,3652.0,2285.0,862.0
70,71,Washington Park West,6393.0,807.0,2365.0,2789.0,432.0,3365.0,1291.0,1457.0
7,8,Berkeley,8112.0,1305.0,2270.0,3513.0,1024.0,4049.0,1843.0,1510.0
41,42,Lowry Field,8067.0,2000.0,2190.0,3163.0,714.0,3829.0,1844.0,1459.0
34,35,Harvey Park South,8393.0,2065.0,2098.0,3025.0,1205.0,3102.0,2062.0,640.0
30,31,Hale,6936.0,987.0,2059.0,3263.0,627.0,3884.0,1395.0,1038.0
47,48,North Park Hill,9382.0,2179.0,2012.0,3887.0,1304.0,3859.0,2398.0,1519.0
48,49,Northeast Park Hill,7822.0,2198.0,1995.0,2734.0,895.0,2723.0,1692.0,385.0
55,56,Sloan Lake,7238.0,1324.0,1973.0,2924.0,1017.0,3499.0,1644.0,1177.0
56,57,South Park Hill,8590.0,1851.0,1843.0,4009.0,887.0,3449.0,2169.0,1733.0
26,27,Fort Logan,8532.0,1796.0,1742.0,3466.0,1528.0,3314.0,2238.0,1040.0
29,30,Goldsmith,5808.0,1060.0,1736.0,2040.0,972.0,2762.0,1176.0,280.0
18,19,College View - South Platte,6498.0,2037.0,1710.0,2336.0,415.0,2038.0,1395.0,129.0
24,25,Elyria Swansea,6401.0,2322.0,1676.0,1960.0,443.0,1695.0,1305.0,191.0
3,4,Barnum,6111.0,2015.0,1647.0,2089.0,360.0,1782.0,1289.0,120.0
69,70,Washington Park,6905.0,1199.0,1589.0,3276.0,841.0,3307.0,1695.0,1739.0
64,65,University Hills,5327.0,925.0,1339.0,2252.0,811.0,2509.0,1251.0,890.0
12,13,Cherry Creek,5589.0,413.0,1314.0,2523.0,1339.0,3542.0,1194.0,1818.0
36,37,Hilltop,8190.0,2016.0,994.0,3676.0,1504.0,3383.0,2218.0,2110.0

# The chart above displays neighborhoods in Denver with the greatest target population for the Coffee Shop in descending order.

## The top three neighborhoods are **Capitol Hill** with a target population of 8,274, **Gateway - Green Valley Ranch** with a target population of 7,778, and **Montbello** with a target population of 7,742.

In [ ]:
coffee_df[coffee_df['NUM_HHLD_100K+'] > 0].sort_values(by=['NUM_HHLD_100K+'], ascending=False)

,NBHD_ID,NBHD_NAME,POPULATION_2010,AGE_LESS_18,AGE_18_TO_34,AGE_35_TO_65,AGE_65_PLUS,NUM_HOUSEHOLDS,FAMILIES,NUM_HHLD_100K+
59,60,Central Park,13948.0,3516.0,4008.0,6045.0,379.0,4092.0,2759.0,2748.0
27,28,Gateway - Green Valley Ranch,29201.0,10074.0,7778.0,10405.0,944.0,9427.0,7056.0,2192.0
31,32,Hampden,17547.0,2754.0,4655.0,6957.0,3181.0,9320.0,4105.0,2160.0
32,33,Hampden South,14370.0,2639.0,3729.0,5650.0,2352.0,7243.0,3481.0,2158.0
36,37,Hilltop,8190.0,2016.0,994.0,3676.0,1504.0,3383.0,2218.0,2110.0
12,13,Cherry Creek,5589.0,413.0,1314.0,2523.0,1339.0,3542.0,1194.0,1818.0
69,70,Washington Park,6905.0,1199.0,1589.0,3276.0,841.0,3307.0,1695.0,1739.0
56,57,South Park Hill,8590.0,1851.0,1843.0,4009.0,887.0,3449.0,2169.0,1733.0
74,75,West Highland,8540.0,1304.0,2555.0,3756.0,925.0,4256.0,1853.0,1725.0
35,36,Highland,8429.0,1296.0,3269.0,3070.0,794.0,4131.0,1495.0,1704.0
58,59,Speer,10954.0,707.0,5361.0,3970.0,916.0,7304.0,1400.0,1682.0
19,20,Congress Park,10235.0,1427.0,3614.0,4450.0,744.0,5724.0,1940.0,1680.0
25,26,Five Points,12712.0,1446.0,5961.0,4660.0,645.0,6406.0,1711.0,1680.0
47,48,North Park Hill,9382.0,2179.0,2012.0,3887.0,1304.0,3859.0,2398.0,1519.0
7,8,Berkeley,8112.0,1305.0,2270.0,3513.0,1024.0,4049.0,1843.0,1510.0
41,42,Lowry Field,8067.0,2000.0,2190.0,3163.0,714.0,3829.0,1844.0,1459.0
70,71,Washington Park West,6393.0,807.0,2365.0,2789.0,432.0,3365.0,1291.0,1457.0
8,9,Capitol Hill,14708.0,408.0,8274.0,5155.0,871.0,10856.0,1201.0,1223.0
55,56,Sloan Lake,7238.0,1324.0,1973.0,2924.0,1017.0,3499.0,1644.0,1177.0
43,44,Marston,11132.0,2266.0,3119.0,4553.0,1194.0,5206.0,2821.0,1164.0
68,69,Virginia Village,12844.0,2421.0,3754.0,5058.0,1611.0,6056.0,2860.0,1129.0
65,66,University Park,7491.0,1135.0,2936.0,2559.0,861.0,3663.0,1408.0,1080.0
11,12,Cheesman Park,7971.0,510.0,3268.0,3241.0,952.0,5343.0,1000.0,1055.0
71,72,Washington Virginia Vale,13030.0,2252.0,3984.0,4798.0,1996.0,6646.0,2808.0,1047.0
26,27,Fort Logan,8532.0,1796.0,1742.0,3466.0,1528.0,3314.0,2238.0,1040.0
30,31,Hale,6936.0,987.0,2059.0,3263.0,627.0,3884.0,1395.0,1038.0
46,47,North Capitol Hill,5823.0,194.0,3238.0,1968.0,423.0,3851.0,461.0,1010.0
63,64,University,9375.0,826.0,5784.0,2246.0,519.0,3759.0,1218.0,991.0
44,45,Montbello,30348.0,11137.0,7742.0,9561.0,1908.0,7942.0,6399.0,939.0
64,65,University Hills,5327.0,925.0,1339.0,2252.0,811.0,2509.0,1251.0,890.0
5,6,Bear Valley,8889.0,2036.0,2375.0,3190.0,1288.0,3652.0,2285.0,862.0
61,62,Sunnyside,9726.0,2363.0,2829.0,3593.0,941.0,3781.0,2222.0,851.0
77,78,Windsor,12589.0,1819.0,3302.0,4085.0,3383.0,7204.0,2590.0,723.0
34,35,Harvey Park South,8393.0,2065.0,2098.0,3025.0,1205.0,3102.0,2062.0,640.0
33,34,Harvey Park,11525.0,3162.0,3005.0,4107.0,1251.0,3990.0,2772.0,476.0
23,24,East Colfax,10191.0,2595.0,3397.0,3640.0,559.0,4273.0,2106.0,442.0
73,74,West Colfax,9740.0,2756.0,2935.0,3111.0,938.0,3703.0,1971.0,431.0
0,1,Athmar Park,8898.0,2649.0,2406.0,3112.0,731.0,2781.0,1964.0,425.0
42,43,Mar Lee,12452.0,3685.0,3256.0,4289.0,1222.0,3973.0,2771.0,413.0
48,49,Northeast Park Hill,7822.0,2198.0,1995.0,2734.0,895.0,2723.0,1692.0,385.0
53,54,Ruby Hill,9820.0,2865.0,2397.0,3440.0,1118.0,3324.0,2146.0,364.0
40,41,Lincoln Park,6119.0,1365.0,2457.0,1867.0,430.0,2741.0,1044.0,364.0
75,76,Westwood,15486.0,5678.0,4037.0,4712.0,1059.0,4340.0,3306.0,326.0
67,68,Villa Park,8758.0,2741.0,2422.0,2912.0,683.0,2819.0,1834.0,291.0
29,30,Goldsmith,5808.0,1060.0,1736.0,2040.0,972.0,2762.0,1176.0,280.0
24,25,Elyria Swansea,6401.0,2322.0,1676.0,1960.0,443.0,1695.0,1305.0,191.0
18,19,College View - South Platte,6498.0,2037.0,1710.0,2336.0,415.0,2038.0,1395.0,129.0
3,4,Barnum,6111.0,2015.0,1647.0,2089.0,360.0,1782.0,1289.0,120.0

# The chart above displays neighborhoods in Denver with households whose income is above 100k in descending order.

## The top three neighborhoods are **Central Park** with 2,748 households above 100k in income, **Gateway - Green Valley Ranch** with 2,192 households above 100k in income, and **Hampden** with 2,160 households above 100k in income.

# Across both charts the **Gateway - Green Valley Ranch** neighborhood was a close second in target population and having large numbers of households with incomes above 100k.

## Therefore, the most optimal neighborhood for the coffee shop to open stores in should be **Gateway - Green Valley Ranch**.